name: Software Composition Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  
  build:
    runs-on: ubuntu-latest  
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true
